version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    environment: 
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password 
      DB_NAME: promon
      JWT_SECRET: promon_secret
  database:
    image: postgres:14.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: promon